In [1]:
#to use colab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
#importing modules
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

%matplotlib inline
import pylab #draw figures

In [4]:
#getting file directories
csv_list = ["/content/drive/MyDrive/final커텍마/기업지표/기업지표-네이버.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-LG CNS.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-당근마켓.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-라인플러스.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-롯데정보통신.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-무신사.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-비바리퍼블리카.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-삼성SDS.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-신세계아이앤씨.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-안랩.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-엔씨소프트.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-우아한형제들.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-카카오.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-쿠팡.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-크래프톤.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-티맥스소프트.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-포스코ICT.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-하이퍼커넥트.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-한국IBM.csv",
            "/content/drive/MyDrive/final커텍마/기업지표/기업지표-한글과컴퓨터.csv"
            ]


In [5]:
#examining test dataset 
test = pd.read_csv("/content/drive/MyDrive/final커텍마/기업지표/기업지표-네이버.csv")

In [6]:
test

네이버    2016    2017    2018  ...      2021     2022     2023 Unnamed: 9
0         매출액  40,226  46,785  55,869  ...    67,882   83,014   98,303         *억
1        영업이익  11,020  11,792   9,425  ...    13,652   17,552   22,081        NaN
2       당기순이익   7,591   7,701   6,279  ...   165,754   18,201   21,716        NaN
3       영업이익률    27.4    25.2   16.87  ...     20.11    21.14    22.46        NaN
4        순이익률   18.87   16.46   11.24  ...    244.18    21.93    22.09        NaN
5      ROE(%)    26.2    18.5   12.97  ...    106.66     7.53     8.37        NaN
6      ROA(%)   14.11    10.7    7.02  ...     65.83     5.28     5.85        NaN
7        자산총계  63,706  80,193  98,812  ...   333,451  355,944  386,051        NaN
8        자본총계  41,296  53,052  59,491  ...   245,001  261,927  283,907        NaN
9        부채총계  22,410  27,141  39,320  ...    88,450   94,017  102,144        NaN
10     매출액증가율     NaN    16.3   19.42  ...     27.98      NaN      NaN        NaN
11    영업이익증가율     NaN       7  -20.07  ...     12.33      NaN      NaN        NaN
12     순이익증가율     NaN    1.45  -18.46  ...  1,861.59      NaN      NaN        NaN
13     총자산증가율     NaN   25.88   23.22  ...     95.98      NaN      NaN        NaN
14        EPS   4,546   4,689   3,937  ...   100,977   11,288   13,533        NaN
15        BPS  24,957  32,429  35,847  ...   159,097  170,861  185,206        NaN
16        SPS     NaN  28,386  33,898  ...    41,325      NaN      NaN        NaN
17        PER   34.09    37.1   30.99  ...      4.07    36.37    30.33        NaN
18        PBR    6.21    5.37     3.4  ...      2.58      2.4     2.22        NaN
19        PSR     NaN    6.13     3.6  ...      9.96      NaN      NaN        NaN
20  EV/EBITDA     NaN    18.4   14.34  ...     33.97      NaN      NaN        NaN
21      직원 현황   2,693   2,793   3,585  ...       NaN      NaN      NaN        NaN
22    평균 근속연수    5.45    5.32    5.29  ...       NaN      NaN      NaN        NaN
23  1인 평균 급여액  69,579  82,332  77,069  ...       NaN      NaN      NaN         *천

[24 rows x 10 columns]

우선적으로 2018-2020년에 대한 영업이익, 당기순이익, 직원수 데이터를 가져오기 위한 코드를 실행했다.

In [7]:
#영업이익
y_2020_m = []

for csv in csv_list:
  df_y = pd.read_csv(csv)
  if type(df_y['2020'][2])==str:
    yval = int(df_y['2020'][2].replace(",",""))
    y_2020_m.append(yval)
  else:
    y_2020_m.append(df_y['2020'][2])


In [8]:
#직원수
y_2020_p =[]
for csv in csv_list:
  df_y = pd.read_csv(csv)
  if type(df_y['2020'][21])==str:
    yval = float(df_y['2020'][21].replace(",",""))
    y_2020_p.append(yval)
  else:
    y_2020_p.append(df_y['2020'][21])

In [9]:
#순이익증가율
y_2020_i =[]
for csv in csv_list:
  df_y = pd.read_csv(csv)
  if type(df_y['2020'][12])==str:
    yval = float(df_y['2020'][12].replace(",",""))
    y_2020_i.append(yval)
  else:
    y_2020_i.append(df_y['2020'][12])

In [10]:
#영업이익
y_2019_m = []

for csv in csv_list:
  df_y = pd.read_csv(csv)
  if type(df_y['2019'][2])==str:
    yval = int(df_y['2019'][2].replace(",",""))
    y_2019_m.append(yval)
  else:
    y_2019_m.append(df_y['2019'][2])


In [11]:
#직원수
y_2019_p =[]
for csv in csv_list:
  df_y = pd.read_csv(csv)
  if type(df_y['2019'][21])==str:
    yval = float(df_y['2019'][21].replace(",",""))
    y_2019_p.append(yval)
  else:
    y_2019_p.append(df_y['2019'][21])

In [12]:
#순이익증가율
y_2019_i =[]
for csv in csv_list:
  df_y = pd.read_csv(csv)
  if type(df_y['2019'][12])==str:
    yval = float(df_y['2019'][12].replace(",",""))
    y_2019_i.append(yval)
  else:
    y_2019_i.append(df_y['2019'][12])

In [13]:
#당기순이익
y_2018_m = []

for csv in csv_list:
  df_y = pd.read_csv(csv)
  if type(df_y['2018'][2])==str:
    yval = int(df_y['2018'][2].replace(",",""))
    y_2018_m.append(yval)
  else:
    y_2018_m.append(df_y['2018'][2])


In [14]:
y_2018_p =[]
for csv in csv_list:
  df_y = pd.read_csv(csv)
  if type(df_y['2018'][21])==str:
    yval = float(df_y['2018'][21].replace(",",""))
    y_2018_p.append(yval)
  else:
    y_2018_p.append(df_y['2018'][21])

In [15]:
#순이익증가율
y_2018_i =[]
for csv in csv_list:
  df_y = pd.read_csv(csv)
  if type(df_y['2018'][12])==str:
    yval = float(df_y['2018'][12].replace(",",""))
    y_2018_i.append(yval)
  else:
    y_2018_i.append(df_y['2018'][12])

In [16]:
print(y_2018_m)
print(y_2019_m)
print(y_2020_m)

[6279, 1105, nan, -136, 234, 220, -444, 6388, 293, 228, 4215, 62, 159, -11443, 2510, 177, -342, 170, 172, 108]
[3968, 1634, nan, -448, 530, 380, -1244, 7504, 107, 191, 3592, -452, -3419, -7232, 2789, 186, 397, 210, 62, 221]
[8450, 1664, nan, 331, 299, 263, -893, 4529, 696, 185, 5866, 2140, 1734, -6144, 5563, 176, 90, 200, 66, 466]


가져온 데이터로 각 변수 별 데이터셋을 만들었다.

In [17]:
colName = ["네이버",'LG CNS','당근마켓','라인플러스','롯데정보통신','무신사',
           '비바리퍼블리카','삼성SDS','신세계아이앤씨','안랩','엔씨소프트','우아한형제들',
           '카카오', '쿠팡','크래프톤','티맥스소프트','포스코ICT','하이퍼커넥트','한국IBM','한글과컴퓨터']
y_m = pd.DataFrame([y_2018_m, y_2019_m, y_2020_m], columns = colName).T


In [18]:
#당기순이익
y_m = y_m.fillna(value = 100)
y_m

0       1       2
네이버       6279.0  3968.0  8450.0
LG CNS    1105.0  1634.0  1664.0
당근마켓       100.0   100.0   100.0
라인플러스     -136.0  -448.0   331.0
롯데정보통신     234.0   530.0   299.0
무신사        220.0   380.0   263.0
비바리퍼블리카   -444.0 -1244.0  -893.0
삼성SDS     6388.0  7504.0  4529.0
신세계아이앤씨    293.0   107.0   696.0
안랩         228.0   191.0   185.0
엔씨소프트     4215.0  3592.0  5866.0
우아한형제들      62.0  -452.0  2140.0
카카오        159.0 -3419.0  1734.0
쿠팡      -11443.0 -7232.0 -6144.0
크래프톤      2510.0  2789.0  5563.0
티맥스소프트     177.0   186.0   176.0
포스코ICT    -342.0   397.0    90.0
하이퍼커넥트     170.0   210.0   200.0
한국IBM      172.0    62.0    66.0
한글과컴퓨터     108.0   221.0   466.0

In [19]:
#직원수
y_p = pd.DataFrame([y_2018_p, y_2019_p, y_2020_p], columns = colName).T
y_p = y_p.fillna(value = 100) #결측치 처리
y_p

0         1         2
네이버       3585.00   3492.00   4076.00
LG CNS    5842.00   6173.00   6175.00
당근마켓       100.00    100.00    100.00
라인플러스     1130.00   1194.00   1138.00
롯데정보통신    2090.00   2784.00   2803.00
무신사        184.00    407.00    595.00
비바리퍼블리카    174.00    336.00    464.00
삼성SDS    12677.00  12501.00  12323.00
신세계아이앤씨    729.00    867.00    923.00
안랩        1133.00   1187.00   1206.00
엔씨소프트       14.04     19.69     20.95
우아한형제들     734.00    926.00   1180.00
카카오       2705.00   2701.00   2837.00
쿠팡        6372.00   9540.00  23299.00
크래프톤       583.00    726.00   1171.00
티맥스소프트     515.00    601.00    562.00
포스코ICT    2535.00   2469.00   2064.00
하이퍼커넥트     180.00    274.00    360.00
한국IBM     1599.00   1408.00   1247.00
한글과컴퓨터     479.00    415.00    415.00

In [20]:
#순이익증가율
y_i = pd.DataFrame([y_2018_i, y_2019_i, y_2020_i], columns = colName).T
y_i = y_i.fillna(value = 0)
y_i

0        1       2
네이버      -18.46   -36.80  112.94
LG CNS    -6.99    47.87    1.84
당근마켓       0.00     0.00    0.00
라인플러스   -111.63   229.41 -173.88
롯데정보통신   854.33   126.79  -43.64
무신사       18.28    72.73  -30.79
비바리퍼블리카   13.85   180.18  -28.22
삼성SDS     17.91    17.48  -39.65
신세계아이앤씨  194.96   -63.57  552.83
안랩        40.34   -16.21   -3.47
엔씨소프트     -5.08   -14.79   63.33
우아한형제들   -70.62  -829.03 -573.45
카카오      -87.30 -2251.98  150.70
쿠팡        69.90   -36.80  -15.04
크래프톤       0.00    11.10   99.48
티맥스소프트   268.75     5.08   -5.38
포스코ICT  -181.34   216.14  -77.32
하이퍼커넥트   136.11    23.53   -4.76
한국IBM    -61.00   -63.95    6.45
한글과컴퓨터   -47.36   105.69  110.67

In [21]:
#별점정보 파일 디렉토리
csv_list3 = ['/content/drive/MyDrive/final커텍마/csv/NAVER.csv',
             '/content/drive/MyDrive/final커텍마/csv/LG%20CNS.csv',
             '/content/drive/MyDrive/final커텍마/csv/당근마켓.csv',
             '/content/drive/MyDrive/final커텍마/csv/라인플러스.csv',
             '/content/drive/MyDrive/final커텍마/csv/롯데정보통신.csv',
             '/content/drive/MyDrive/final커텍마/csv/무신사.csv',
             '/content/drive/MyDrive/final커텍마/csv/비바리퍼블리카 (1).csv',
             '/content/drive/MyDrive/final커텍마/csv/삼성SDS.csv',
            '/content/drive/MyDrive/final커텍마/csv/신세계아이앤씨.csv',
             '/content/drive/MyDrive/final커텍마/csv/AhnLab.csv',
             '/content/drive/MyDrive/final커텍마/csv/NCSOFT.csv',
             '/content/drive/MyDrive/final커텍마/csv/우아한형제들.csv',
             '/content/drive/MyDrive/final커텍마/csv/카카오.csv',
             '/content/drive/MyDrive/final커텍마/csv/COUPANG.csv',
             '/content/drive/MyDrive/final커텍마/csv/크래프톤.csv',
             '/content/drive/MyDrive/final커텍마/csv/티맥스소프트.csv',
             '/content/drive/MyDrive/final커텍마/csv/포스코ICT.csv',
             '/content/drive/MyDrive/final커텍마/csv/하이퍼커넥트.csv',
             '/content/drive/MyDrive/final커텍마/csv/한국IBM.csv',
             '/content/drive/MyDrive/final커텍마/csv/한글과컴퓨터.csv'
             ]

In [22]:
#별점정보 추출 전처리
def getX(csv):
  df_x = pd.read_csv(csv)
  df_x = df_x.fillna(value = 0)
  career = np.mean(df_x['career'].to_numpy())
  life = np.mean(df_x['life'].to_numpy())
  money = np.mean(df_x['money'].to_numpy())
  culture = np.mean(df_x['culture'].to_numpy())
  manager = np.mean(df_x['manager'].to_numpy())
  xval = [career, life, money, culture, manager]
  return xval

In [23]:
x=[]
for csv in csv_list3:
  xval = getX(csv)
  x.append(xval)

In [24]:
#별점정보 추출결과
x= pd.DataFrame(x)
x.head

<bound method NDFrame.head of            0         1         2         3         4
0   3.708187  3.230409  3.488304  3.377778  2.610526
1   2.391667  2.677500  2.405000  2.698333  1.738333
2   4.800000  3.883333  4.550000  4.800000  4.583333
3   3.892063  3.911111  3.957143  3.934921  2.979365
4   2.034615  3.130769  1.926923  2.234615  1.632051
5   3.004167  3.316667  2.862500  2.362500  2.241667
6   4.281818  2.345455  4.436364  3.854545  3.815152
7   2.538333  3.942500  3.617500  3.053333  1.945833
8   2.503704  3.259259  3.348148  2.788889  2.840741
9   3.266667  4.100000  2.315152  3.333333  2.093939
10  3.411594  3.595652  4.082609  3.327536  2.862319
11  3.843137  3.560784  4.254902  4.186275  3.647059
12  3.282883  3.948649  2.665766  3.431532  2.437838
13  3.557692  3.148718  3.175641  3.378846  2.955769
14  3.366667  2.820000  3.833333  3.186667  2.780000
15  2.508696  3.220290  3.397101  2.910145  1.705797
16  2.438889  3.366667  2.238889  2.511111  1.655556
17  3.587500  4.

In [26]:
#당기순이익 선형회귀
lr = LinearRegression()
lr_m = lr.fit(x,y_m)

In [27]:
#변수 결과
lr_m.coef_

array([[   10.31653403,   982.64832781,  3649.144404  ,  -285.98006979,
        -3623.43733472],
       [ -622.37161023,   781.02738909,  3650.5721059 ,  -527.58072791,
        -3052.64182745],
       [  926.70240479,   268.27164979,  3184.08328597,  -624.77271401,
        -3270.0681706 ]])

In [28]:
#실제 예측값 -> 부정확한 것으로 드러남
value = [[5,5,5,5,5]]
lr_m.predict(value)

array([[ -868.88330592, -1427.38617138,  -128.23101671]])

In [29]:
#직원수에 대한 선형회귀
lr_p = lr.fit(x, y_p)

In [30]:
#2020년의 직원수
y_2020_p1 = pd.DataFrame(y_2020_p)
y_2020_p1 = y_2020_p1.fillna(100)
y_2020_p1

0
0    4076.00
1    6175.00
2     100.00
3    1138.00
4    2803.00
5     595.00
6     464.00
7   12323.00
8     923.00
9    1206.00
10     20.95
11   1180.00
12   2837.00
13  23299.00
14   1171.00
15    562.00
16   2064.00
17    360.00
18   1247.00
19    415.00

In [31]:
#2020년 직원수에 대한 선형회귀
lr_p2020 = lr.fit(x,y_2020_p1)

In [32]:
lr_p2020.predict(value)

array([[830.94960661]])

In [33]:
lr_p.coef_

array([[-1268.77793869, -1258.82012178,  -798.67483826,  3206.09777273,
         -945.04930253]])

In [34]:
lr_p.predict(value)

array([[830.94960661]])

In [35]:
#순이익증가율에 대한 선형회귀
lr_i = lr.fit(x, y_i)


In [36]:
lr_i.coef_

array([[-217.04571133,   30.96956272,  -23.44274683,  -47.81634232,
         176.72022649],
       [ 359.99245908, -195.25459552,  345.79496244, -594.02095613,
        -211.41574534],
       [ -26.12548925,   62.93018646,  -11.4388543 , -281.65141455,
         193.61976377]])

In [37]:
lr_i.predict(value)

array([[  12.35567512, -751.49113916,    8.20661929]])

In [38]:
def getX2(csv):
  df_x = pd.read_csv(csv)
  df_x = df_x.fillna(value = 0)
  career = df_x['career'].to_numpy()
  life =df_x['life'].to_numpy()
  money = df_x['money'].to_numpy()
  culture = df_x['culture'].to_numpy()
  manager = df_x['manager'].to_numpy()
  xval = np.array([career, life, money, culture, manager])
  return xval


In [43]:
value1 = [[3,3,3,3,3]]

In [45]:
#직원수 스케일링
y_p_scaled = y_p*0.01

In [46]:
#스케일링 결과에 대한 선형회귀분석
lr_p_scaled = lr.fit(x, y_p_scaled)

In [47]:
lr_p_scaled.coef_

array([[-26.1800553 ,  -2.39050002,   8.49205896,  41.20769762,
        -26.0322937 ],
       [-25.3642719 ,  -4.60696547,   4.77048159,  39.52675674,
        -21.21528736],
       [-12.68777939, -12.58820122,  -7.98674838,  32.06097773,
         -9.45049303]])

In [48]:
lr_p_scaled.predict(value)

array([[-4.82057658, -2.29067155,  8.30949607]])

In [50]:
#y 를 binary 변수로 변형 test
def setY1(csv):
   df_y = pd.read_csv(csv)
   binary = 0
   if type(df_y['2018'][12])==str:
      yval = float(df_y['2018'][12].replace(",",""))
   else:
      yval = df_y['2018'][12]
   if yval > 0 :  binary = 1
   return binary

In [51]:
#general versionn of y to binary function
def setY(year, index, csv):
   df_y = pd.read_csv(csv)
   binary = 0
   if type(df_y[year][index])==str:
      yval = float(df_y[year][index].replace(",",""))
   else:
      yval = df_y[year][index]
   if yval > 0 :  binary =1
   return binary

In [52]:
y_binary = []
for csv in csv_list:
  y_binary.append(setY1(csv))

In [53]:
y_binary

[0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0]

In [54]:
y_binary2 = []
for csv in csv_list:
  y_binary2.append(setY('2019',12, csv))

In [55]:
y_binary2

[0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1]

In [56]:
from sklearn.linear_model import LogisticRegression

In [57]:
#logistic regression to binary y
lor = LogisticRegression()
lor.fit(x, y_binary)

LogisticRegression()

In [58]:
#better coefficient result
lor1 = lor.fit(x, y_binary)
lor1.coef_

array([[-0.26438808,  0.24006832,  0.3054004 , -0.51166954,  0.02085802]])

In [59]:
#score better
lor1.score(x,y_binary2)

0.7

In [60]:
#making all Y's binary
y_binary_all= []
for i in [2, 12, 21]:
  y_val = []
  for csv in csv_list:
    y_val.append(setY('2019',i,csv))
  y_binary_all.append(y_val)

y_binary_all

[[1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1],
 [0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1],
 [1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

In [61]:
y_binary_all[0]

[1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1]

In [62]:
#당기순이익에 대한 로지스틱 회귀분석
lor_m = lor.fit(x,y_binary_all[0])

print(lor_m.coef_)


[[-0.77245906 -0.06740618  0.00216265 -0.94040309 -0.95942429]]


In [63]:
#순이익증가율에 대한 로지스틱 회귀분석
lor_i = lor.fit(x,y_binary_all[1])

print(lor_i.coef_)

[[-0.36873475 -0.57604438  0.59938636 -0.58236295 -0.75462417]]


In [64]:
#직원수에 대한 로지스틱 회귀분석 -> 비논리적인 분석임을 파악
lor_p = lor.fit(x,y_binary_all[2])

print(lor_p.coef_)

[[-0.57036808 -0.29352139 -0.34944577 -0.58741589 -0.75975794]]


In [65]:
#더 나은 결과를 위해 x를 표준화 
from sklearn.preprocessing import StandardScaler
x_standadized_skl = StandardScaler().fit_transform(x)
x_standadized_skl


array([[ 0.70816418, -0.3054139 ,  0.31149673,  0.26431723,  0.08933213],
       [-1.03634808, -1.42306766, -1.00330448, -0.73713048, -0.99430437],
       [ 2.15491794,  1.01440991,  1.60007217,  2.36056102,  2.54040173],
       [ 0.95181748,  1.07056005,  0.88052418,  1.08550202,  0.54758754],
       [-1.5094743 , -0.50682696, -1.58354424, -1.42061429, -1.12635211],
       [-0.22472852, -0.13105294, -0.44803883, -1.23212242, -0.36894922],
       [ 1.46827876, -2.09426602,  1.46215224,  0.96703532,  1.58599155],
       [-0.84200109,  1.13400971,  0.4683012 , -0.21388838, -0.73650068],
       [-0.88788857, -0.24709657,  0.1413901 , -0.60365871,  0.37535685],
       [ 0.12310843,  1.452381  , -1.11235317,  0.19880962, -0.55248964],
       [ 0.31515092,  0.43288977,  1.03280149,  0.19026514,  0.40216608],
       [ 0.88698566,  0.3624077 ,  1.24191303,  1.45597788,  1.37714857],
       [ 0.14459643,  1.14643862, -0.68681426,  0.34354604, -0.12522077],
       [ 0.50874452, -0.47054533, -0.0

In [66]:
#표준화한 x 에대해 당기순이익에 대한 로지스틱 회귀분석 진행
lor_m_std = lor.fit(x_standadized_skl,y_binary_all[0])
lor_m_std.coef_

array([[-0.67646621, -0.03638299,  0.17341387, -1.00382837, -0.89346742]])

In [67]:
#표준화한 x에 대해 순이익 증가율에 대한 로지스틱 회귀분석 진행
lor_i_std = lor.fit(x_standadized_skl, y_binary_all[1])
lor_i_std.coef_

array([[-0.24027414, -0.45301   ,  0.68969556, -0.5074967 , -0.79323817]])

In [69]:
#표준화한 x에 대해 스케일링한 직원수에 대한 선형회귀분석 진행
lr_p_std = lr.fit(x_standadized_skl, y_p_scaled[2])
lr_p_std.coef_

array([-9.57500935, -6.2274512 , -6.58052123, 21.75216231, -7.60647473])